image:
  repository: n8nio/n8n
  pullPolicy: IfNotPresent
  tag: ""

db:
  type: sqlite

main:
  count: 1
  persistence:
    enabled: true
    size: 5Gi
    storageClass: standard
    mountPath: /home/node/.n8n

  extraEnvVars:
    N8N_ENCRYPTION_KEY: "74e8d57f999d03e7e98f73d5526a2173"
    N8N_BASIC_AUTH_ACTIVE: "true"
    N8N_SECURE_COOKIE: "false"
    N8N_BASIC_AUTH_USER: "admin"
    N8N_BASIC_AUTH_PASSWORD: "changeme123"
    WEBHOOK_URL: "http://localhost:5678"
    GENERIC_TIMEZONE: "Africa/Nairobi"

service:
  type: ClusterIP
  port: 5678

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: n8n.local
      paths:
       - path: /
         pathType: Prefix
  tls:
    - secretName: n8n-tls
      hosts:
        - n8n.local

redis:
  enabled: true
  auth:
    enabled: true
    password: admin123
